package verified
/**
 * AUTO-GENERATED FILE — DO NOT MODIFY
 *
 * This file was generated by Isabelle's code extraction facility from the
 * mechanised proof of POSIX lexing based on Sulzmann and Lu's 2014 paper.
 *
 * Source formalisation:
 *   Ausaf, Dyckhoff, and Urban
 *   "POSIX Lexing with Derivatives of Regular Expressions"
 *   Archive of Formal Proofs (Posix-Lexing entry, Simplifying3 theory)
 *   https://www.isa-afp.org/entries/Posix-Lexing.html
 *
 * The entry point is slexer, which implements a verified POSIX lexer with
 * simplification. Given a regular expression (rexp) and an input (List),
 * it returns an Option[vala] — a POSIX parse tree if the input matches,
 * or None otherwise.
 *
 * Key types:
 *   rexp[A]  — regular expressions (Zero, One, Atom, Plus, Times, Star, ...)
 *   vala[A]  — POSIX values / parse trees (Void, Atm, Seq, Left, Right, Stars, ...)
 *   char     — Isabelle characters (8 booleans encoding a byte)
 *   nat      — Peano natural numbers (zero_nat, Suc)
 *
 * Isabelle version: 2025-2
 * AFP version:      2026-03-22
 */

object SLULexer {

def list_all[A](p : A => Boolean, x1 : List[A]) : Boolean = (p, x1) match {
  case (p, Nil) => true
  case (p, x :: xs) => p(x) && list_all[A](p, xs)
}

abstract sealed class set[A]
final case class seta[A](a : List[A]) extends set[A]
final case class coset[A](a : List[A]) extends set[A]

trait equal[A] {
  val `SLULexer.equal` : (A, A) => Boolean
}
def equal[A](a : A, b : A)(implicit A: equal[A]) : Boolean =
  A.`SLULexer.equal`(a, b)
object equal {
  implicit def `SLULexer.equal_char` : equal[char] = new equal[char] {
    val `SLULexer.equal` = (a : char, b : char) => equal_chara(a, b)
  }
  implicit def `SLULexer.equal_set`[A : equal] : equal[set[A]] = new
    equal[set[A]] {
    val `SLULexer.equal` = (a : set[A], b : set[A]) => equal_seta[A](a, b)
  }
}

def eq[A : equal](a : A, b : A) : Boolean = equal[A](a, b)

def membera[A : equal](x0 : List[A], y : A) : Boolean = (x0, y) match {
  case (Nil, y) => false
  case (x :: xs, y) => eq[A](x, y) || membera[A](xs, y)
}

def member[A : equal](x : A, xa1 : set[A]) : Boolean = (x, xa1) match {
  case (x, seta(xs)) => membera[A](xs, x)
  case (x, coset(xs)) => ! (membera[A](xs, x))
}

def less_eq_set[A : equal](a : set[A], b : set[A]) : Boolean = (a, b) match {
  case (seta(xs), b) => list_all[A](((x : A) => member[A](x, b)), xs)
  case (a, coset(ys)) => list_all[A](((y : A) => ! (member[A](y, a))), ys)
  case (coset(Nil), seta(Nil)) => false
}

def equal_seta[A : equal](a : set[A], b : set[A]) : Boolean =
  less_eq_set[A](a, b) && less_eq_set[A](b, a)

def equal_bool(p : Boolean, pa : Boolean) : Boolean = (p, pa) match {
  case (false, p) => ! p
  case (true, p) => p
  case (p, false) => ! p
  case (p, true) => p
}

abstract sealed class char
final case class Char(a : Boolean, b : Boolean, c : Boolean, d : Boolean,
                       e : Boolean, f : Boolean, g : Boolean, h : Boolean)
  extends char

def equal_chara(x0 : char, x1 : char) : Boolean = (x0, x1) match {
  case (Char(x1, x2, x3, x4, x5, x6, x7, x8),
         Char(y1, y2, y3, y4, y5, y6, y7, y8))
    => equal_bool(x1, y1) &&
         (equal_bool(x2, y2) &&
           (equal_bool(x3, y3) &&
             (equal_bool(x4, y4) &&
               (equal_bool(x5, y5) &&
                 (equal_bool(x6, y6) &&
                   (equal_bool(x7, y7) && equal_bool(x8, y8)))))))
}

abstract sealed class nat
final case class zero_nat() extends nat
final case class Suc(a : nat) extends nat

abstract sealed class vala[A]
final case class Void[A]() extends vala[A]
final case class Atm[A](a : A) extends vala[A]
final case class Seq[A](a : vala[A], b : vala[A]) extends vala[A]
final case class Right[A](a : vala[A]) extends vala[A]
final case class Left[A](a : vala[A]) extends vala[A]
final case class Stars[A](a : List[vala[A]]) extends vala[A]
final case class Recv[A](a : List[char], b : vala[A]) extends vala[A]

abstract sealed class rexp[A]
final case class Zero[A]() extends rexp[A]
final case class One[A]() extends rexp[A]
final case class Atom[A](a : A) extends rexp[A]
final case class Plus[A](a : rexp[A], b : rexp[A]) extends rexp[A]
final case class Times[A](a : rexp[A], b : rexp[A]) extends rexp[A]
final case class Star[A](a : rexp[A]) extends rexp[A]
final case class NTimes[A](a : rexp[A], b : nat) extends rexp[A]
final case class Upto[A](a : rexp[A], b : nat) extends rexp[A]
final case class From[A](a : rexp[A], b : nat) extends rexp[A]
final case class Rec[A](a : List[char], b : rexp[A]) extends rexp[A]
final case class Charset[A](a : set[A]) extends rexp[A]

def id[A] : A => A = ((x : A) => x)

def equal_nat(x0 : nat, x1 : nat) : Boolean = (x0, x1) match {
  case (zero_nat(), Suc(x2)) => false
  case (Suc(x2), zero_nat()) => false
  case (Suc(x2), Suc(y2)) => equal_nat(x2, y2)
  case (zero_nat(), zero_nat()) => true
}

def nullable[A](x0 : rexp[A]) : Boolean = x0 match {
  case Zero() => false
  case One() => true
  case Atom(c) => false
  case Plus(r1, r2) => nullable[A](r1) || nullable[A](r2)
  case Times(r1, r2) => nullable[A](r1) && nullable[A](r2)
  case Star(r) => true
  case NTimes(r, n) =>
    (equal_nat(n, zero_nat()) match { case true => true
      case false => nullable[A](r) })
  case Upto(r, n) => true
  case From(r, n) =>
    (equal_nat(n, zero_nat()) match { case true => true
      case false => nullable[A](r) })
  case Rec(l, r) => nullable[A](r)
  case Charset(cs) => false
}

def replicate[A](xa0 : nat, x : A) : List[A] = (xa0, x) match {
  case (zero_nat(), x) => Nil
  case (Suc(n), x) => x :: replicate[A](n, x)
}

def mkeps[A](x0 : rexp[A]) : vala[A] = x0 match {
  case One() => Void[A]()
  case Times(r1, r2) => Seq[A](mkeps[A](r1), mkeps[A](r2))
  case Plus(r1, r2) =>
    (nullable[A](r1) match { case true => Left[A](mkeps[A](r1))
      case false => Right[A](mkeps[A](r2)) })
  case Star(r) => Stars[A](Nil)
  case Upto(r, n) => Stars[A](Nil)
  case NTimes(r, n) => Stars[A](replicate[vala[A]](n, mkeps[A](r)))
  case From(r, n) => Stars[A](replicate[vala[A]](n, mkeps[A](r)))
  case Rec(l, r) => Recv[A](l, mkeps[A](r))
}

def injval[A](x0 : rexp[A], c : A, v : vala[A]) : vala[A] = (x0, c, v) match {
  case (Atom(d), c, Void()) => Atm[A](c)
  case (Plus(r1, r2), c, Left(v1)) => Left[A](injval[A](r1, c, v1))
  case (Plus(r1, r2), c, Right(v2)) => Right[A](injval[A](r2, c, v2))
  case (Times(r1, r2), c, Seq(v1, v2)) => Seq[A](injval[A](r1, c, v1), v2)
  case (Times(r1, r2), c, Left(Seq(v1, v2))) => Seq[A](injval[A](r1, c, v1), v2)
  case (Times(r1, r2), c, Right(v2)) =>
    Seq[A](mkeps[A](r1), injval[A](r2, c, v2))
  case (Star(r), c, Seq(v, Stars(vs))) => Stars[A](injval[A](r, c, v) :: vs)
  case (NTimes(r, n), c, Seq(v, Stars(vs))) =>
    Stars[A](injval[A](r, c, v) :: vs)
  case (Upto(r, n), c, Seq(v, Stars(vs))) => Stars[A](injval[A](r, c, v) :: vs)
  case (From(r, n), c, Seq(v, Stars(vs))) => Stars[A](injval[A](r, c, v) :: vs)
  case (Rec(l, r), c, v) => Recv[A](l, injval[A](r, c, v))
  case (Charset(cs), c, Void()) => Atm[A](c)
}

def F_Times2[A, B,
              C](f_1 : A => vala[B], f_2 : (vala[C]) => vala[B],
                  v : A) : vala[B]
  =
  Seq[B](f_1(v), f_2(Void[C]()))

def F_Times1[A, B,
              C](f_1 : (vala[A]) => vala[B], f_2 : C => vala[B],
                  v : C) : vala[B]
  =
  Seq[B](f_1(Void[A]()), f_2(v))

def F_Times[A](f_1 : (vala[A]) => vala[A], f_2 : (vala[A]) => vala[A],
                x2 : vala[A]) : vala[A]
  =
  (f_1, f_2, x2) match {
  case (f_1, f_2, Seq(v_1, v_2)) => Seq[A](f_1(v_1), f_2(v_2))
  case (f1, f2, Void()) => Void[A]()
  case (f1, f2, Atm(va)) => Atm[A](va)
  case (f1, f2, Right(va)) => Right[A](va)
  case (f1, f2, Left(va)) => Left[A](va)
  case (f1, f2, Stars(va)) => Stars[A](va)
  case (f1, f2, Recv(va, vb)) => Recv[A](va, vb)
}

def simp_Times[A, B](x0 : (rexp[A], (vala[B]) => vala[B]),
                      x1 : (rexp[A],
                             (vala[B]) =>
                               vala[B])) : (rexp[A], (vala[B]) => vala[B])
  =
  (x0, x1) match {
  case ((Zero(), f_1), (r_2, f_2)) => (Zero[A](), sys.error("undefined"))
  case ((One(), f_1), (Zero(), f_2)) => (Zero[A](), sys.error("undefined"))
  case ((Atom(v), f_1), (Zero(), f_2)) => (Zero[A](), sys.error("undefined"))
  case ((Plus(v, va), f_1), (Zero(), f_2)) =>
    (Zero[A](), sys.error("undefined"))
  case ((Times(v, va), f_1), (Zero(), f_2)) =>
    (Zero[A](), sys.error("undefined"))
  case ((Star(v), f_1), (Zero(), f_2)) => (Zero[A](), sys.error("undefined"))
  case ((NTimes(v, va), f_1), (Zero(), f_2)) =>
    (Zero[A](), sys.error("undefined"))
  case ((Upto(v, va), f_1), (Zero(), f_2)) =>
    (Zero[A](), sys.error("undefined"))
  case ((From(v, va), f_1), (Zero(), f_2)) =>
    (Zero[A](), sys.error("undefined"))
  case ((Rec(v, va), f_1), (Zero(), f_2)) => (Zero[A](), sys.error("undefined"))
  case ((Charset(v), f_1), (Zero(), f_2)) => (Zero[A](), sys.error("undefined"))
  case ((One(), f_1), (One(), f_2)) =>
    (One[A](), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (Atom(v), f_2)) =>
    (Atom[A](v), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (Plus(v, va), f_2)) =>
    (Plus[A](v, va), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (Times(v, va), f_2)) =>
    (Times[A](v, va), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (Star(v), f_2)) =>
    (Star[A](v), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (NTimes(v, va), f_2)) =>
    (NTimes[A](v, va), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (Upto(v, va), f_2)) =>
    (Upto[A](v, va), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (From(v, va), f_2)) =>
    (From[A](v, va), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (Rec(v, va), f_2)) =>
    (Rec[A](v, va), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((One(), f_1), (Charset(v), f_2)) =>
    (Charset[A](v), ((a : vala[B]) => F_Times1[B, B, vala[B]](f_1, f_2, a)))
  case ((Atom(v), f_1), (One(), f_2)) =>
    (Atom[A](v), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (One(), f_2)) =>
    (Plus[A](v, va), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (One(), f_2)) =>
    (Times[A](v, va), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((Star(v), f_1), (One(), f_2)) =>
    (Star[A](v), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (One(), f_2)) =>
    (NTimes[A](v, va), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (One(), f_2)) =>
    (Upto[A](v, va), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((From(v, va), f_1), (One(), f_2)) =>
    (From[A](v, va), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (One(), f_2)) =>
    (Rec[A](v, va), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((Charset(v), f_1), (One(), f_2)) =>
    (Charset[A](v), ((a : vala[B]) => F_Times2[vala[B], B, B](f_1, f_2, a)))
  case ((Atom(v), f_1), (Atom(va), f_2)) =>
    (Times[A](Atom[A](v), Atom[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (Plus(va, vb), f_2)) =>
    (Times[A](Atom[A](v), Plus[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (Times(va, vb), f_2)) =>
    (Times[A](Atom[A](v), Times[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (Star(va), f_2)) =>
    (Times[A](Atom[A](v), Star[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (NTimes(va, vb), f_2)) =>
    (Times[A](Atom[A](v), NTimes[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (Upto(va, vb), f_2)) =>
    (Times[A](Atom[A](v), Upto[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (From(va, vb), f_2)) =>
    (Times[A](Atom[A](v), From[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (Rec(va, vb), f_2)) =>
    (Times[A](Atom[A](v), Rec[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Atom(v), f_1), (Charset(va), f_2)) =>
    (Times[A](Atom[A](v), Charset[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (Atom(vb), f_2)) =>
    (Times[A](Plus[A](v, va), Atom[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (Times[A](Plus[A](v, va), Plus[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (Times(vb, vc), f_2)) =>
    (Times[A](Plus[A](v, va), Times[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (Star(vb), f_2)) =>
    (Times[A](Plus[A](v, va), Star[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (Times[A](Plus[A](v, va), NTimes[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (Times[A](Plus[A](v, va), Upto[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (From(vb, vc), f_2)) =>
    (Times[A](Plus[A](v, va), From[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (Times[A](Plus[A](v, va), Rec[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Plus(v, va), f_1), (Charset(vb), f_2)) =>
    (Times[A](Plus[A](v, va), Charset[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (Atom(vb), f_2)) =>
    (Times[A](Times[A](v, va), Atom[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (Times[A](Times[A](v, va), Plus[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (Times(vb, vc), f_2)) =>
    (Times[A](Times[A](v, va), Times[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (Star(vb), f_2)) =>
    (Times[A](Times[A](v, va), Star[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (Times[A](Times[A](v, va), NTimes[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (Times[A](Times[A](v, va), Upto[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (From(vb, vc), f_2)) =>
    (Times[A](Times[A](v, va), From[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (Times[A](Times[A](v, va), Rec[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Times(v, va), f_1), (Charset(vb), f_2)) =>
    (Times[A](Times[A](v, va), Charset[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (Atom(va), f_2)) =>
    (Times[A](Star[A](v), Atom[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (Plus(va, vb), f_2)) =>
    (Times[A](Star[A](v), Plus[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (Times(va, vb), f_2)) =>
    (Times[A](Star[A](v), Times[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (Star(va), f_2)) =>
    (Times[A](Star[A](v), Star[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (NTimes(va, vb), f_2)) =>
    (Times[A](Star[A](v), NTimes[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (Upto(va, vb), f_2)) =>
    (Times[A](Star[A](v), Upto[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (From(va, vb), f_2)) =>
    (Times[A](Star[A](v), From[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (Rec(va, vb), f_2)) =>
    (Times[A](Star[A](v), Rec[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Star(v), f_1), (Charset(va), f_2)) =>
    (Times[A](Star[A](v), Charset[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (Atom(vb), f_2)) =>
    (Times[A](NTimes[A](v, va), Atom[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (Times[A](NTimes[A](v, va), Plus[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (Times(vb, vc), f_2)) =>
    (Times[A](NTimes[A](v, va), Times[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (Star(vb), f_2)) =>
    (Times[A](NTimes[A](v, va), Star[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (Times[A](NTimes[A](v, va), NTimes[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (Times[A](NTimes[A](v, va), Upto[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (From(vb, vc), f_2)) =>
    (Times[A](NTimes[A](v, va), From[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (Times[A](NTimes[A](v, va), Rec[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((NTimes(v, va), f_1), (Charset(vb), f_2)) =>
    (Times[A](NTimes[A](v, va), Charset[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (Atom(vb), f_2)) =>
    (Times[A](Upto[A](v, va), Atom[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (Times[A](Upto[A](v, va), Plus[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (Times(vb, vc), f_2)) =>
    (Times[A](Upto[A](v, va), Times[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (Star(vb), f_2)) =>
    (Times[A](Upto[A](v, va), Star[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (Times[A](Upto[A](v, va), NTimes[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (Times[A](Upto[A](v, va), Upto[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (From(vb, vc), f_2)) =>
    (Times[A](Upto[A](v, va), From[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (Times[A](Upto[A](v, va), Rec[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Upto(v, va), f_1), (Charset(vb), f_2)) =>
    (Times[A](Upto[A](v, va), Charset[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (Atom(vb), f_2)) =>
    (Times[A](From[A](v, va), Atom[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (Times[A](From[A](v, va), Plus[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (Times(vb, vc), f_2)) =>
    (Times[A](From[A](v, va), Times[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (Star(vb), f_2)) =>
    (Times[A](From[A](v, va), Star[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (Times[A](From[A](v, va), NTimes[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (Times[A](From[A](v, va), Upto[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (From(vb, vc), f_2)) =>
    (Times[A](From[A](v, va), From[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (Times[A](From[A](v, va), Rec[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((From(v, va), f_1), (Charset(vb), f_2)) =>
    (Times[A](From[A](v, va), Charset[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (Atom(vb), f_2)) =>
    (Times[A](Rec[A](v, va), Atom[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (Times[A](Rec[A](v, va), Plus[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (Times(vb, vc), f_2)) =>
    (Times[A](Rec[A](v, va), Times[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (Star(vb), f_2)) =>
    (Times[A](Rec[A](v, va), Star[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (Times[A](Rec[A](v, va), NTimes[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (Times[A](Rec[A](v, va), Upto[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (From(vb, vc), f_2)) =>
    (Times[A](Rec[A](v, va), From[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (Times[A](Rec[A](v, va), Rec[A](vb, vc)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Rec(v, va), f_1), (Charset(vb), f_2)) =>
    (Times[A](Rec[A](v, va), Charset[A](vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (Atom(va), f_2)) =>
    (Times[A](Charset[A](v), Atom[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (Plus(va, vb), f_2)) =>
    (Times[A](Charset[A](v), Plus[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (Times(va, vb), f_2)) =>
    (Times[A](Charset[A](v), Times[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (Star(va), f_2)) =>
    (Times[A](Charset[A](v), Star[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (NTimes(va, vb), f_2)) =>
    (Times[A](Charset[A](v), NTimes[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (Upto(va, vb), f_2)) =>
    (Times[A](Charset[A](v), Upto[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (From(va, vb), f_2)) =>
    (Times[A](Charset[A](v), From[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (Rec(va, vb), f_2)) =>
    (Times[A](Charset[A](v), Rec[A](va, vb)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
  case ((Charset(v), f_1), (Charset(va), f_2)) =>
    (Times[A](Charset[A](v), Charset[A](va)),
      ((a : vala[B]) => F_Times[B](f_1, f_2, a)))
}

def equal_list[A : equal](x0 : List[A], x1 : List[A]) : Boolean = (x0, x1)
  match {
  case (Nil, x21 :: x22) => false
  case (x21 :: x22, Nil) => false
  case (x21 :: x22, y21 :: y22) => eq[A](x21, y21) && equal_list[A](x22, y22)
  case (Nil, Nil) => true
}

def equal_rexp[A : equal](x0 : rexp[A], x1 : rexp[A]) : Boolean = (x0, x1)
  match {
  case (Rec(x101, x102), Charset(x11)) => false
  case (Charset(x11), Rec(x101, x102)) => false
  case (From(x91, x92), Charset(x11)) => false
  case (Charset(x11), From(x91, x92)) => false
  case (From(x91, x92), Rec(x101, x102)) => false
  case (Rec(x101, x102), From(x91, x92)) => false
  case (Upto(x81, x82), Charset(x11)) => false
  case (Charset(x11), Upto(x81, x82)) => false
  case (Upto(x81, x82), Rec(x101, x102)) => false
  case (Rec(x101, x102), Upto(x81, x82)) => false
  case (Upto(x81, x82), From(x91, x92)) => false
  case (From(x91, x92), Upto(x81, x82)) => false
  case (NTimes(x71, x72), Charset(x11)) => false
  case (Charset(x11), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), Rec(x101, x102)) => false
  case (Rec(x101, x102), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), From(x91, x92)) => false
  case (From(x91, x92), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), Upto(x81, x82)) => false
  case (Upto(x81, x82), NTimes(x71, x72)) => false
  case (Star(x6), Charset(x11)) => false
  case (Charset(x11), Star(x6)) => false
  case (Star(x6), Rec(x101, x102)) => false
  case (Rec(x101, x102), Star(x6)) => false
  case (Star(x6), From(x91, x92)) => false
  case (From(x91, x92), Star(x6)) => false
  case (Star(x6), Upto(x81, x82)) => false
  case (Upto(x81, x82), Star(x6)) => false
  case (Star(x6), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), Star(x6)) => false
  case (Times(x51, x52), Charset(x11)) => false
  case (Charset(x11), Times(x51, x52)) => false
  case (Times(x51, x52), Rec(x101, x102)) => false
  case (Rec(x101, x102), Times(x51, x52)) => false
  case (Times(x51, x52), From(x91, x92)) => false
  case (From(x91, x92), Times(x51, x52)) => false
  case (Times(x51, x52), Upto(x81, x82)) => false
  case (Upto(x81, x82), Times(x51, x52)) => false
  case (Times(x51, x52), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), Times(x51, x52)) => false
  case (Times(x51, x52), Star(x6)) => false
  case (Star(x6), Times(x51, x52)) => false
  case (Plus(x41, x42), Charset(x11)) => false
  case (Charset(x11), Plus(x41, x42)) => false
  case (Plus(x41, x42), Rec(x101, x102)) => false
  case (Rec(x101, x102), Plus(x41, x42)) => false
  case (Plus(x41, x42), From(x91, x92)) => false
  case (From(x91, x92), Plus(x41, x42)) => false
  case (Plus(x41, x42), Upto(x81, x82)) => false
  case (Upto(x81, x82), Plus(x41, x42)) => false
  case (Plus(x41, x42), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), Plus(x41, x42)) => false
  case (Plus(x41, x42), Star(x6)) => false
  case (Star(x6), Plus(x41, x42)) => false
  case (Plus(x41, x42), Times(x51, x52)) => false
  case (Times(x51, x52), Plus(x41, x42)) => false
  case (Atom(x3), Charset(x11)) => false
  case (Charset(x11), Atom(x3)) => false
  case (Atom(x3), Rec(x101, x102)) => false
  case (Rec(x101, x102), Atom(x3)) => false
  case (Atom(x3), From(x91, x92)) => false
  case (From(x91, x92), Atom(x3)) => false
  case (Atom(x3), Upto(x81, x82)) => false
  case (Upto(x81, x82), Atom(x3)) => false
  case (Atom(x3), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), Atom(x3)) => false
  case (Atom(x3), Star(x6)) => false
  case (Star(x6), Atom(x3)) => false
  case (Atom(x3), Times(x51, x52)) => false
  case (Times(x51, x52), Atom(x3)) => false
  case (Atom(x3), Plus(x41, x42)) => false
  case (Plus(x41, x42), Atom(x3)) => false
  case (One(), Charset(x11)) => false
  case (Charset(x11), One()) => false
  case (One(), Rec(x101, x102)) => false
  case (Rec(x101, x102), One()) => false
  case (One(), From(x91, x92)) => false
  case (From(x91, x92), One()) => false
  case (One(), Upto(x81, x82)) => false
  case (Upto(x81, x82), One()) => false
  case (One(), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), One()) => false
  case (One(), Star(x6)) => false
  case (Star(x6), One()) => false
  case (One(), Times(x51, x52)) => false
  case (Times(x51, x52), One()) => false
  case (One(), Plus(x41, x42)) => false
  case (Plus(x41, x42), One()) => false
  case (One(), Atom(x3)) => false
  case (Atom(x3), One()) => false
  case (Zero(), Charset(x11)) => false
  case (Charset(x11), Zero()) => false
  case (Zero(), Rec(x101, x102)) => false
  case (Rec(x101, x102), Zero()) => false
  case (Zero(), From(x91, x92)) => false
  case (From(x91, x92), Zero()) => false
  case (Zero(), Upto(x81, x82)) => false
  case (Upto(x81, x82), Zero()) => false
  case (Zero(), NTimes(x71, x72)) => false
  case (NTimes(x71, x72), Zero()) => false
  case (Zero(), Star(x6)) => false
  case (Star(x6), Zero()) => false
  case (Zero(), Times(x51, x52)) => false
  case (Times(x51, x52), Zero()) => false
  case (Zero(), Plus(x41, x42)) => false
  case (Plus(x41, x42), Zero()) => false
  case (Zero(), Atom(x3)) => false
  case (Atom(x3), Zero()) => false
  case (Zero(), One()) => false
  case (One(), Zero()) => false
  case (Charset(x11), Charset(y11)) => eq[set[A]](x11, y11)
  case (Rec(x101, x102), Rec(y101, y102)) =>
    equal_list[char](x101, y101) && equal_rexp[A](x102, y102)
  case (From(x91, x92), From(y91, y92)) =>
    equal_rexp[A](x91, y91) && equal_nat(x92, y92)
  case (Upto(x81, x82), Upto(y81, y82)) =>
    equal_rexp[A](x81, y81) && equal_nat(x82, y82)
  case (NTimes(x71, x72), NTimes(y71, y72)) =>
    equal_rexp[A](x71, y71) && equal_nat(x72, y72)
  case (Star(x6), Star(y6)) => equal_rexp[A](x6, y6)
  case (Times(x51, x52), Times(y51, y52)) =>
    equal_rexp[A](x51, y51) && equal_rexp[A](x52, y52)
  case (Plus(x41, x42), Plus(y41, y42)) =>
    equal_rexp[A](x41, y41) && equal_rexp[A](x42, y42)
  case (Atom(x3), Atom(y3)) => eq[A](x3, y3)
  case (One(), One()) => true
  case (Zero(), Zero()) => true
}

def F_RIGHT[A, B](f : A => vala[B], v : A) : vala[B] = Right[B](f(v))

def F_Plus[A](f_1 : (vala[A]) => vala[A], f_2 : (vala[A]) => vala[A],
               x2 : vala[A]) : vala[A]
  =
  (f_1, f_2, x2) match {
  case (f_1, f_2, Right(v)) => Right[A](f_2(v))
  case (f_1, f_2, Left(v)) => Left[A](f_1(v))
  case (f1, f2, Void()) => Void[A]()
  case (f1, f2, Atm(va)) => Atm[A](va)
  case (f1, f2, Seq(va, vb)) => Seq[A](va, vb)
  case (f1, f2, Stars(va)) => Stars[A](va)
  case (f1, f2, Recv(va, vb)) => Recv[A](va, vb)
}

def F_LEFT[A, B](f : A => vala[B], v : A) : vala[B] = Left[B](f(v))

def simp_Plus[A : equal,
               B](x0 : (rexp[A], (vala[B]) => vala[B]),
                   x1 : (rexp[A],
                          (vala[B]) =>
                            vala[B])) : (rexp[A], (vala[B]) => vala[B])
  =
  (x0, x1) match {
  case ((Zero(), f_1), (r_2, f_2)) =>
    (r_2, ((a : vala[B]) => F_RIGHT[vala[B], B](f_2, a)))
  case ((One(), f_1), (Zero(), f_2)) =>
    (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((Atom(v), f_1), (Zero(), f_2)) =>
    (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((Plus(v, va), f_1), (Zero(), f_2)) =>
    (Plus[A](v, va), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((Times(v, va), f_1), (Zero(), f_2)) =>
    (Times[A](v, va), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((Star(v), f_1), (Zero(), f_2)) =>
    (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((NTimes(v, va), f_1), (Zero(), f_2)) =>
    (NTimes[A](v, va), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((Upto(v, va), f_1), (Zero(), f_2)) =>
    (Upto[A](v, va), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((From(v, va), f_1), (Zero(), f_2)) =>
    (From[A](v, va), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((Rec(v, va), f_1), (Zero(), f_2)) =>
    (Rec[A](v, va), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((Charset(v), f_1), (Zero(), f_2)) =>
    (Charset[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
  case ((One(), f_1), (One(), f_2)) =>
    (equal_rexp[A](One[A](), One[A]()) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (Atom(v), f_2)) =>
    (equal_rexp[A](One[A](), Atom[A](v)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), Atom[A](v)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (Plus(v, va), f_2)) =>
    (equal_rexp[A](One[A](), Plus[A](v, va)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), Plus[A](v, va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (Times(v, va), f_2)) =>
    (equal_rexp[A](One[A](), Times[A](v, va)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), Times[A](v, va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (Star(v), f_2)) =>
    (equal_rexp[A](One[A](), Star[A](v)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), Star[A](v)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (NTimes(v, va), f_2)) =>
    (equal_rexp[A](One[A](), NTimes[A](v, va)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), NTimes[A](v, va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (Upto(v, va), f_2)) =>
    (equal_rexp[A](One[A](), Upto[A](v, va)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), Upto[A](v, va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (From(v, va), f_2)) =>
    (equal_rexp[A](One[A](), From[A](v, va)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), From[A](v, va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (Rec(v, va), f_2)) =>
    (equal_rexp[A](One[A](), Rec[A](v, va)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), Rec[A](v, va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((One(), f_1), (Charset(v), f_2)) =>
    (equal_rexp[A](One[A](), Charset[A](v)) match {
      case true => (One[A](), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](One[A](), Charset[A](v)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (One(), f_2)) =>
    (equal_rexp[A](Atom[A](v), One[A]()) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (Atom(va), f_2)) =>
    (equal_rexp[A](Atom[A](v), Atom[A](va)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), Atom[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (Plus(va, vb), f_2)) =>
    (equal_rexp[A](Atom[A](v), Plus[A](va, vb)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), Plus[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (Times(va, vb), f_2)) =>
    (equal_rexp[A](Atom[A](v), Times[A](va, vb)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), Times[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (Star(va), f_2)) =>
    (equal_rexp[A](Atom[A](v), Star[A](va)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), Star[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (NTimes(va, vb), f_2)) =>
    (equal_rexp[A](Atom[A](v), NTimes[A](va, vb)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), NTimes[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (Upto(va, vb), f_2)) =>
    (equal_rexp[A](Atom[A](v), Upto[A](va, vb)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), Upto[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (From(va, vb), f_2)) =>
    (equal_rexp[A](Atom[A](v), From[A](va, vb)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), From[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (Rec(va, vb), f_2)) =>
    (equal_rexp[A](Atom[A](v), Rec[A](va, vb)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), Rec[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Atom(v), f_1), (Charset(va), f_2)) =>
    (equal_rexp[A](Atom[A](v), Charset[A](va)) match {
      case true => (Atom[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Atom[A](v), Charset[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (One(), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), One[A]()) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (Atom(vb), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), Atom[A](vb)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), Atom[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), Plus[A](vb, vc)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), Plus[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (Times(vb, vc), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), Times[A](vb, vc)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), Times[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (Star(vb), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), Star[A](vb)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), Star[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), NTimes[A](vb, vc)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), NTimes[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), Upto[A](vb, vc)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), Upto[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (From(vb, vc), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), From[A](vb, vc)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), From[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), Rec[A](vb, vc)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), Rec[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Plus(v, va), f_1), (Charset(vb), f_2)) =>
    (equal_rexp[A](Plus[A](v, va), Charset[A](vb)) match {
      case true => (Plus[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Plus[A](v, va), Charset[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (One(), f_2)) =>
    (equal_rexp[A](Times[A](v, va), One[A]()) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (Atom(vb), f_2)) =>
    (equal_rexp[A](Times[A](v, va), Atom[A](vb)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), Atom[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (equal_rexp[A](Times[A](v, va), Plus[A](vb, vc)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), Plus[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (Times(vb, vc), f_2)) =>
    (equal_rexp[A](Times[A](v, va), Times[A](vb, vc)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), Times[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (Star(vb), f_2)) =>
    (equal_rexp[A](Times[A](v, va), Star[A](vb)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), Star[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (equal_rexp[A](Times[A](v, va), NTimes[A](vb, vc)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), NTimes[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (equal_rexp[A](Times[A](v, va), Upto[A](vb, vc)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), Upto[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (From(vb, vc), f_2)) =>
    (equal_rexp[A](Times[A](v, va), From[A](vb, vc)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), From[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (equal_rexp[A](Times[A](v, va), Rec[A](vb, vc)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), Rec[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Times(v, va), f_1), (Charset(vb), f_2)) =>
    (equal_rexp[A](Times[A](v, va), Charset[A](vb)) match {
      case true => (Times[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Times[A](v, va), Charset[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (One(), f_2)) =>
    (equal_rexp[A](Star[A](v), One[A]()) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (Atom(va), f_2)) =>
    (equal_rexp[A](Star[A](v), Atom[A](va)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), Atom[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (Plus(va, vb), f_2)) =>
    (equal_rexp[A](Star[A](v), Plus[A](va, vb)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), Plus[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (Times(va, vb), f_2)) =>
    (equal_rexp[A](Star[A](v), Times[A](va, vb)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), Times[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (Star(va), f_2)) =>
    (equal_rexp[A](Star[A](v), Star[A](va)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), Star[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (NTimes(va, vb), f_2)) =>
    (equal_rexp[A](Star[A](v), NTimes[A](va, vb)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), NTimes[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (Upto(va, vb), f_2)) =>
    (equal_rexp[A](Star[A](v), Upto[A](va, vb)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), Upto[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (From(va, vb), f_2)) =>
    (equal_rexp[A](Star[A](v), From[A](va, vb)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), From[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (Rec(va, vb), f_2)) =>
    (equal_rexp[A](Star[A](v), Rec[A](va, vb)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), Rec[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Star(v), f_1), (Charset(va), f_2)) =>
    (equal_rexp[A](Star[A](v), Charset[A](va)) match {
      case true => (Star[A](v), ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Star[A](v), Charset[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (One(), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), One[A]()) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (Atom(vb), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), Atom[A](vb)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), Atom[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), Plus[A](vb, vc)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), Plus[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (Times(vb, vc), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), Times[A](vb, vc)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), Times[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (Star(vb), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), Star[A](vb)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), Star[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), NTimes[A](vb, vc)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), NTimes[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), Upto[A](vb, vc)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), Upto[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (From(vb, vc), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), From[A](vb, vc)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), From[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), Rec[A](vb, vc)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), Rec[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((NTimes(v, va), f_1), (Charset(vb), f_2)) =>
    (equal_rexp[A](NTimes[A](v, va), Charset[A](vb)) match {
      case true => (NTimes[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](NTimes[A](v, va), Charset[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (One(), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), One[A]()) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (Atom(vb), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), Atom[A](vb)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), Atom[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), Plus[A](vb, vc)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), Plus[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (Times(vb, vc), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), Times[A](vb, vc)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), Times[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (Star(vb), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), Star[A](vb)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), Star[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), NTimes[A](vb, vc)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), NTimes[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), Upto[A](vb, vc)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), Upto[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (From(vb, vc), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), From[A](vb, vc)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), From[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), Rec[A](vb, vc)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), Rec[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Upto(v, va), f_1), (Charset(vb), f_2)) =>
    (equal_rexp[A](Upto[A](v, va), Charset[A](vb)) match {
      case true => (Upto[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Upto[A](v, va), Charset[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (One(), f_2)) =>
    (equal_rexp[A](From[A](v, va), One[A]()) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (Atom(vb), f_2)) =>
    (equal_rexp[A](From[A](v, va), Atom[A](vb)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), Atom[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (equal_rexp[A](From[A](v, va), Plus[A](vb, vc)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), Plus[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (Times(vb, vc), f_2)) =>
    (equal_rexp[A](From[A](v, va), Times[A](vb, vc)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), Times[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (Star(vb), f_2)) =>
    (equal_rexp[A](From[A](v, va), Star[A](vb)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), Star[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (equal_rexp[A](From[A](v, va), NTimes[A](vb, vc)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), NTimes[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (equal_rexp[A](From[A](v, va), Upto[A](vb, vc)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), Upto[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (From(vb, vc), f_2)) =>
    (equal_rexp[A](From[A](v, va), From[A](vb, vc)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), From[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (equal_rexp[A](From[A](v, va), Rec[A](vb, vc)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), Rec[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((From(v, va), f_1), (Charset(vb), f_2)) =>
    (equal_rexp[A](From[A](v, va), Charset[A](vb)) match {
      case true => (From[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](From[A](v, va), Charset[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (One(), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), One[A]()) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (Atom(vb), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), Atom[A](vb)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), Atom[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (Plus(vb, vc), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), Plus[A](vb, vc)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), Plus[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (Times(vb, vc), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), Times[A](vb, vc)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), Times[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (Star(vb), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), Star[A](vb)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), Star[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (NTimes(vb, vc), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), NTimes[A](vb, vc)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), NTimes[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (Upto(vb, vc), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), Upto[A](vb, vc)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), Upto[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (From(vb, vc), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), From[A](vb, vc)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), From[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (Rec(vb, vc), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), Rec[A](vb, vc)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), Rec[A](vb, vc)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Rec(v, va), f_1), (Charset(vb), f_2)) =>
    (equal_rexp[A](Rec[A](v, va), Charset[A](vb)) match {
      case true => (Rec[A](v, va),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Rec[A](v, va), Charset[A](vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (One(), f_2)) =>
    (equal_rexp[A](Charset[A](v), One[A]()) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), One[A]()),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (Atom(va), f_2)) =>
    (equal_rexp[A](Charset[A](v), Atom[A](va)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), Atom[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (Plus(va, vb), f_2)) =>
    (equal_rexp[A](Charset[A](v), Plus[A](va, vb)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), Plus[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (Times(va, vb), f_2)) =>
    (equal_rexp[A](Charset[A](v), Times[A](va, vb)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), Times[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (Star(va), f_2)) =>
    (equal_rexp[A](Charset[A](v), Star[A](va)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), Star[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (NTimes(va, vb), f_2)) =>
    (equal_rexp[A](Charset[A](v), NTimes[A](va, vb)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), NTimes[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (Upto(va, vb), f_2)) =>
    (equal_rexp[A](Charset[A](v), Upto[A](va, vb)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), Upto[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (From(va, vb), f_2)) =>
    (equal_rexp[A](Charset[A](v), From[A](va, vb)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), From[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (Rec(va, vb), f_2)) =>
    (equal_rexp[A](Charset[A](v), Rec[A](va, vb)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), Rec[A](va, vb)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
  case ((Charset(v), f_1), (Charset(va), f_2)) =>
    (equal_rexp[A](Charset[A](v), Charset[A](va)) match {
      case true => (Charset[A](v),
                     ((a : vala[B]) => F_LEFT[vala[B], B](f_1, a)))
      case false => (Plus[A](Charset[A](v), Charset[A](va)),
                      ((a : vala[B]) => F_Plus[B](f_1, f_2, a)))
      })
}

def simp[A : equal](x0 : rexp[A]) : (rexp[A], (vala[A]) => vala[A]) = x0 match {
  case Plus(r1, r2) => simp_Plus[A, A](simp[A](r1), simp[A](r2))
  case Times(r1, r2) => simp_Times[A, A](simp[A](r1), simp[A](r2))
  case Zero() => (Zero[A](), id[vala[A]])
  case One() => (One[A](), id[vala[A]])
  case Atom(v) => (Atom[A](v), id[vala[A]])
  case Star(v) => (Star[A](v), id[vala[A]])
  case NTimes(v, va) => (NTimes[A](v, va), id[vala[A]])
  case Upto(v, va) => (Upto[A](v, va), id[vala[A]])
  case From(v, va) => (From[A](v, va), id[vala[A]])
  case Rec(v, va) => (Rec[A](v, va), id[vala[A]])
  case Charset(v) => (Charset[A](v), id[vala[A]])
}

def minus_nat(m : nat, n : nat) : nat = (m, n) match {
  case (m, zero_nat()) => m
  case (zero_nat(), n) => zero_nat()
  case (Suc(m), Suc(n)) => minus_nat(m, n)
}

def one_nat : nat = Suc(zero_nat())

def deriv[A : equal](c : A, x1 : rexp[A]) : rexp[A] = (c, x1) match {
  case (c, Zero()) => Zero[A]()
  case (c, One()) => Zero[A]()
  case (ca, Atom(c)) =>
    (eq[A](ca, c) match { case true => One[A]() case false => Zero[A]() })
  case (c, Plus(r1, r2)) => Plus[A](deriv[A](c, r1), deriv[A](c, r2))
  case (c, Times(r1, r2)) =>
    (nullable[A](r1) match {
      case true => Plus[A](Times[A](deriv[A](c, r1), r2), deriv[A](c, r2))
      case false => Times[A](deriv[A](c, r1), r2) })
  case (c, Star(r)) => Times[A](deriv[A](c, r), Star[A](r))
  case (c, NTimes(r, n)) =>
    (equal_nat(n, zero_nat()) match { case true => Zero[A]()
      case false => Times[A](deriv[A](c, r),
                              NTimes[A](r, minus_nat(n, one_nat)))
      })
  case (c, Upto(r, n)) =>
    (equal_nat(n, zero_nat()) match { case true => Zero[A]()
      case false => Times[A](deriv[A](c, r), Upto[A](r, minus_nat(n, one_nat)))
      })
  case (c, From(r, n)) =>
    (equal_nat(n, zero_nat()) match {
      case true => Times[A](deriv[A](c, r), Star[A](r))
      case false => Times[A](deriv[A](c, r), From[A](r, minus_nat(n, one_nat)))
      })
  case (c, Rec(l, r)) => deriv[A](c, r)
  case (c, Charset(cs)) =>
    (member[A](c, cs) match { case true => One[A]() case false => Zero[A]() })
}

def slexer[A : equal](r : rexp[A], x1 : List[A]) : Option[vala[A]] = (r, x1)
  match {
  case (r, Nil) =>
    (nullable[A](r) match { case true => Some[vala[A]](mkeps[A](r))
      case false => None })
  case (r, c :: s) =>
    {
      val (rs, fr) =
        simp[A](deriv[A](c, r)) : ((rexp[A], (vala[A]) => vala[A]));
      (slexer[A](rs, s) match {
         case None => None
         case Some(v) => Some[vala[A]](injval[A](r, c, fr(v)))
       })
    }
}

} /* object SLULexer */
