package formallex

import rexp.ALT
import rexp.CFUN
import rexp.CHAR
import rexp.ONE
import rexp.PLUS
import rexp.RANGE
import rexp.RECD
import rexp.RegularExpression
import rexp.SEQ
import rexp.STAR
import rexp.ZERO
import value.Chr
import value.Empty
import value.Left
import value.Rec
import value.Right
import value.Seq
import value.Stars
import value.Value
import verified.SLULexer
import scala.jdk.javaapi.CollectionConverters

/**
 * Converts between Verilex's Kotlin types and the Isabelle-extracted Scala types used by the verified lexer.
 *
 * The verified lexer ([verified.SLULexer]) was extracted from an Isabelle/HOL formalisation of
 * Sulzmann and Lu's POSIX lexing algorithm. Because the extraction targets Scala, it uses its own
 * representations for characters ([SLULexer.char] — 8 booleans encoding a byte), natural numbers
 * ([SLULexer.nat] — Peano encoding), regular expressions ([SLULexer.rexp]), and POSIX parse trees
 * ([SLULexer.vala]). This object provides the bidirectional translation layer so that the rest of
 * Verilex can work with Kotlin-native types while delegating actual lexing to the verified code.
 *
 * The translations fall into three groups:
 *
 * 1. **Character / string encoding** — [Char.toIsabelleChar], [SLULexer.char.toKotlinChar],
 *    [String.toIsabelleList]. Isabelle characters are 8-tuples of booleans (LSB-first), so
 *    conversion decomposes / recomposes the character code bitwise.
 *
 * 2. **Regular expression conversion** — [RegularExpression.toRexp]. Maps every Verilex regex
 *    node to its Isabelle counterpart. [PLUS] is desugared into `r · r*` (the Isabelle formalisation
 *    has no native PLUS node). [CFUN] (character-predicate functions) cannot be represented
 *    and will throw.
 *
 * 3. **Value (parse-tree) conversion** — [SLULexer.vala.toKotlinValue]. Walks the Isabelle POSIX
 *    value tree returned by the verified lexer and rebuilds it using Verilex's [Value] hierarchy.
 *
 * Because the Scala code uses `scala.collection.immutable.List` while Kotlin uses
 * `kotlin.collections.List`, two private helpers ([toScalaList] / [toKotlinList]) bridge the
 * collection boundary via [CollectionConverters].
 */
object KotlinScalaConverter {

    /**
     * Converts a Kotlin [List] to a [scala.collection.immutable.List].
     *
     * Required because the Isabelle-extracted Scala code operates exclusively on Scala immutable
     * lists, while Kotlin's standard library collection methods (e.g. [Iterable.map]) produce
     * Kotlin lists. Uses [CollectionConverters] to go through Java interop.
     */
    private fun <T> List<T>.toScalaList(): scala.collection.immutable.List<T> =
        CollectionConverters.asScala(this).toList()

    /**
     * Converts a [scala.collection.immutable.List] to a Kotlin [List].
     *
     * Used when extracting values from the verified lexer's output (e.g. the list of sub-values
     * inside [SLULexer.Stars] or the character list inside [SLULexer.Recv]) so that downstream
     * Kotlin code can process them with familiar Kotlin collection operations.
     */
    private fun <T> scala.collection.immutable.List<T>.toKotlinList(): List<T> =
        CollectionConverters.asJava(this)

    /**
     * Encodes a Kotlin [Char] as an Isabelle character ([SLULexer.char]).
     *
     * Isabelle represents characters as 8-tuples of booleans, one per bit of the byte value,
     * in LSB-first order: field `a` is bit 0 (weight 1), field `b` is bit 1 (weight 2), …,
     * field `h` is bit 7 (weight 128). This matches the `Char` case class generated by Isabelle's
     * code extraction.
     *
     * Only the low 8 bits of the Kotlin character's code point are preserved, which is sufficient
     * for ASCII / Latin-1 source text.
     */
    fun Char.toIsabelleChar(): SLULexer.char =
        SLULexer.Char(
            this.code and 1 != 0,
            this.code and 2 != 0,
            this.code and 4 != 0,
            this.code and 8 != 0,
            this.code and 16 != 0,
            this.code and 32 != 0,
            this.code and 64 != 0,
            this.code and 128 != 0,
        )

    /**
     * Decodes an Isabelle character ([SLULexer.char]) back to a Kotlin [Char].
     *
     * Reverses the encoding performed by [toIsabelleChar]: reads each boolean field from the
     * [SLULexer.Char] case class (`a` through `h`) and reconstructs the integer character code
     * by OR-ing the corresponding bit weights.
     *
     * The field accessors (`a()` through `h()`) are called as methods rather than properties
     * because Scala 3 case class fields are exposed to the JVM as zero-argument methods, not
     * as JavaBean-style getters, and Kotlin does not synthesise `componentN()` operators for them.
     */
    fun SLULexer.char.toKotlinChar(): Char {
        val c = this as SLULexer.Char
        var code = 0
        if (c.a()) code = code or 1
        if (c.b()) code = code or 2
        if (c.c()) code = code or 4
        if (c.d()) code = code or 8
        if (c.e()) code = code or 16
        if (c.f()) code = code or 32
        if (c.g()) code = code or 64
        if (c.h()) code = code or 128
        return code.toChar()
    }

    /**
     * Converts a Kotlin [String] to a `scala.collection.immutable.List<SLULexer.char>`.
     *
     * This is the input format expected by [SLULexer.slexer]: a Scala immutable list of
     * Isabelle-encoded characters. Each Kotlin [Char] in the string is individually converted
     * via [toIsabelleChar], and the resulting Kotlin list is bridged to a Scala list via
     * [toScalaList].
     */
    fun String.toIsabelleList(): scala.collection.immutable.List<SLULexer.char> =
        this.map { it.toIsabelleChar() }.toScalaList()

    /**
     * Converts a Kotlin [Int] to an Isabelle Peano natural number ([SLULexer.nat]).
     *
     * Isabelle's `nat` type uses unary (Peano) representation: `zero_nat` for 0 and `Suc(n)`
     * for the successor of `n`. This is inherently O(n) in the value, so it should only be used
     * for small numbers (e.g. repetition bounds in `NTimes` / `Upto` regex constructors).
     */
    fun Int.toIsabelleNat(): SLULexer.nat {
        var result: SLULexer.nat = SLULexer.zero_nat()
        repeat(this) { result = SLULexer.Suc(result) }
        return result
    }

    /**
     * Converts a Verilex [RegularExpression] to the Isabelle-extracted [SLULexer.rexp] type.
     *
     * The mapping is direct for most constructors:
     *
     * | Verilex              | Isabelle (`SLULexer`)              |
     * |----------------------|------------------------------------|
     * | [ZERO]               | `Zero`                             |
     * | [ONE]                | `One`                              |
     * | [CHAR]               | `Atom(c)`                          |
     * | [RANGE]              | `Charset(seta(cs))`                |
     * | [ALT]                | `Plus(r1, r2)`                     |
     * | [SEQ]                | `Times(r1, r2)`                    |
     * | [STAR]               | `Star(r)`                          |
     * | [PLUS]               | `Times(r, Star(r))` (desugared)    |
     * | [RECD]               | `Rec(name, r)`                     |
     * | [CFUN]               | *unsupported — throws*             |
     *
     * [PLUS] (`r+`) is desugared to `r · r*` because the Isabelle formalisation does not include
     * a native one-or-more repetition constructor. [CFUN] (character-predicate functions) have no
     * analogue in the set-based Isabelle regex type and will cause an [IllegalStateException].
     *
     * Character sets ([RANGE]) are wrapped in [SLULexer.seta] (a finite enumeration set),
     * matching Isabelle's `Charset (set a)` constructor.
     */
    fun RegularExpression.toRexp(): SLULexer.rexp<SLULexer.char> = when (this) {
        is ZERO -> SLULexer.Zero<SLULexer.char>()
        is ONE -> SLULexer.One<SLULexer.char>()
        is CHAR -> SLULexer.Atom<SLULexer.char>(c.toIsabelleChar())
        is RANGE -> SLULexer.Charset<SLULexer.char>(SLULexer.seta<SLULexer.char>(cs.map { it.toIsabelleChar() }.toScalaList()))
        is ALT -> SLULexer.Plus<SLULexer.char>(r1.toRexp(), r2.toRexp())
        is SEQ -> SLULexer.Times<SLULexer.char>(r1.toRexp(), r2.toRexp())
        is STAR -> SLULexer.Star<SLULexer.char>(r.toRexp())
        is PLUS -> SLULexer.Times<SLULexer.char>(r.toRexp(), SLULexer.Star<SLULexer.char>(r.toRexp()))
        is RECD -> SLULexer.Rec<SLULexer.char>(x.toIsabelleList(), r.toRexp())
        is CFUN -> error("CFUN cannot be converted to Isabelle rexp")
    }

    /**
     * Converts an Isabelle POSIX parse tree ([SLULexer.vala]) to a Verilex [Value].
     *
     * After the verified lexer matches an input string against a regular expression, it returns
     * a POSIX value — a tree that records *how* the input was decomposed. This function walks
     * that tree and rebuilds it using Verilex's [Value] sealed hierarchy:
     *
     * | Isabelle (`SLULexer`)  | Verilex ([Value])                            |
     * |-----------------------|----------------------------------------------|
     * | `Void`                | [Empty]                                      |
     * | `Atm(c)`              | [Chr] (character decoded via [toKotlinChar])  |
     * | `Seq(v1, v2)`         | [Seq]                                        |
     * | `Left(v)`             | [Left]                                       |
     * | `Right(v)`            | [Right]                                      |
     * | `Stars(vs)`           | [Stars] (list converted via [toKotlinList])   |
     * | `Recv(name, v)`       | [Rec] (name chars joined into a [String])     |
     *
     * Unchecked casts are required because the Scala generic type parameters are erased at
     * runtime — the `is SLULexer.Atm<*>` pattern match loses the `<SLULexer.char>` type argument.
     * This is safe as long as the value was produced by a lexer instantiated at `SLULexer.char`,
     * which is always the case when called through [FormalLexer.verifiedLex].
     */
    @Suppress("UNCHECKED_CAST")
    fun SLULexer.vala<SLULexer.char>.toKotlinValue(): Value = when (this) {
        is SLULexer.Void -> Empty
        is SLULexer.Atm<*> -> Chr((this.a() as SLULexer.char).toKotlinChar())
        is SLULexer.Seq<*> -> Seq(
            (this.a() as SLULexer.vala<SLULexer.char>).toKotlinValue(),
            (this.b() as SLULexer.vala<SLULexer.char>).toKotlinValue(),
        )
        is SLULexer.Left<*> -> Left((this.a() as SLULexer.vala<SLULexer.char>).toKotlinValue())
        is SLULexer.Right<*> -> Right((this.a() as SLULexer.vala<SLULexer.char>).toKotlinValue())
        is SLULexer.Stars<*> -> Stars(
            (this.a() as scala.collection.immutable.List<SLULexer.vala<SLULexer.char>>)
                .toKotlinList().map { it.toKotlinValue() }
        )
        is SLULexer.Recv<*> -> Rec(
            (this.a() as scala.collection.immutable.List<SLULexer.char>)
                .toKotlinList().map { it.toKotlinChar() }.joinToString(""),
            (this.b() as SLULexer.vala<SLULexer.char>).toKotlinValue(),
        )
        else -> error("Unknown vala type: ${this::class}")
    }

}
